language: python
dist: bionic
sudo: required
python:
  - "3.6"
virtualenv:
  system_site_packages: true

# Install dependencies.
install:
  - pip install -r requirements.txt

script:
 - sudo python3 setup.py install
 - srttotxt -v