# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui',
# licensing of 'ui_mainwindow.ui' applies.
#
# Created: Sat Sep 14 09:59:21 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_read_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_read_file.setObjectName("pushButton_read_file")
        self.gridLayout.addWidget(self.pushButton_read_file, 3, 0, 1, 1)
        self.checkBox_join = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_join.setObjectName("checkBox_join")
        self.gridLayout.addWidget(self.checkBox_join, 7, 1, 1, 1)
        self.pushButton_save_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_file.setObjectName("pushButton_save_file")
        self.gridLayout.addWidget(self.pushButton_save_file, 5, 0, 1, 1)
        self.toolButton_output_file = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_output_file.setObjectName("toolButton_output_file")
        self.gridLayout.addWidget(self.toolButton_output_file, 5, 2, 1, 1)
        self.toolButton_input_file = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_input_file.setObjectName("toolButton_input_file")
        self.gridLayout.addWidget(self.toolButton_input_file, 3, 2, 1, 1)
        self.lineEdit_output_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output_file.setObjectName("lineEdit_output_file")
        self.gridLayout.addWidget(self.lineEdit_output_file, 5, 1, 1, 1)
        self.pushButton_clean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.gridLayout.addWidget(self.pushButton_clean, 6, 0, 1, 1)
        self.lineEdit_input_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_file.setObjectName("lineEdit_input_file")
        self.gridLayout.addWidget(self.lineEdit_input_file, 3, 1, 1, 1)
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.gridLayout.addWidget(self.pushButton_convert, 7, 0, 1, 1)
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.gridLayout.addWidget(self.lineEdit_url, 2, 1, 1, 1)
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setObjectName("pushButton_download")
        self.gridLayout.addWidget(self.pushButton_download, 2, 0, 1, 1)
        self.toolButton_clipboard = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_clipboard.setObjectName("toolButton_clipboard")
        self.gridLayout.addWidget(self.toolButton_clipboard, 2, 2, 1, 1)
        self.toolButton_copy_to_clipboard = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_copy_to_clipboard.setObjectName("toolButton_copy_to_clipboard")
        self.gridLayout.addWidget(self.toolButton_copy_to_clipboard, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_input.setReadOnly(True)
        self.plainTextEdit_input.setObjectName("plainTextEdit_input")
        self.horizontalLayout.addWidget(self.plainTextEdit_input)
        self.plainTextEdit_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_output.setObjectName("plainTextEdit_output")
        self.horizontalLayout.addWidget(self.plainTextEdit_output)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_open_as = QtWidgets.QAction(MainWindow)
        self.action_open_as.setObjectName("action_open_as")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_open_as)
        self.menu.addSeparator()
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_save_as)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.action_about)
        self.menu_2.addAction(self.action_Qt)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.action_open, QtCore.SIGNAL("triggered()"), MainWindow.load_file)
        QtCore.QObject.connect(self.pushButton_convert, QtCore.SIGNAL("clicked()"), MainWindow.convert_srt_to_txt)
        QtCore.QObject.connect(self.pushButton_clean, QtCore.SIGNAL("clicked()"), MainWindow.clean_srt)
        QtCore.QObject.connect(self.action_about, QtCore.SIGNAL("triggered()"), MainWindow.show_about_window)
        QtCore.QObject.connect(self.action_Qt, QtCore.SIGNAL("triggered()"), MainWindow.show_aboutqt_window)
        QtCore.QObject.connect(self.toolButton_input_file, QtCore.SIGNAL("clicked()"), MainWindow.open_file_dialog)
        QtCore.QObject.connect(self.pushButton_read_file, QtCore.SIGNAL("clicked()"), MainWindow.load_file)
        QtCore.QObject.connect(self.toolButton_output_file, QtCore.SIGNAL("clicked()"), MainWindow.set_txt_file_name)
        QtCore.QObject.connect(self.pushButton_save_file, QtCore.SIGNAL("clicked()"), MainWindow.save_file)
        QtCore.QObject.connect(self.action_open_as, QtCore.SIGNAL("triggered()"), MainWindow.open_file_dialog)
        QtCore.QObject.connect(self.action_save, QtCore.SIGNAL("triggered()"), MainWindow.save_file)
        QtCore.QObject.connect(self.action_save_as, QtCore.SIGNAL("triggered()"), MainWindow.save_file_dialog)
        QtCore.QObject.connect(self.pushButton_download, QtCore.SIGNAL("clicked()"), MainWindow.download_subtitle)
        QtCore.QObject.connect(self.toolButton_clipboard, QtCore.SIGNAL("clicked()"), MainWindow.paste_from_clipboard)
        QtCore.QObject.connect(self.toolButton_copy_to_clipboard, QtCore.SIGNAL("clicked()"), MainWindow.copy_to_clipboard)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SRTtoTXT", None, -1))
        self.pushButton_read_file.setText(QtWidgets.QApplication.translate("MainWindow", "Загрузить", None, -1))
        self.checkBox_join.setText(QtWidgets.QApplication.translate("MainWindow", "Объединение строк в предложения", None, -1))
        self.pushButton_save_file.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить", None, -1))
        self.toolButton_output_file.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolButton_input_file.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.pushButton_clean.setText(QtWidgets.QApplication.translate("MainWindow", "Очистка файла от HTML-разметки", None, -1))
        self.pushButton_convert.setText(QtWidgets.QApplication.translate("MainWindow", "Конвертировать", None, -1))
        self.pushButton_download.setText(QtWidgets.QApplication.translate("MainWindow", "Скачать субтитры", None, -1))
        self.toolButton_clipboard.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolButton_copy_to_clipboard.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Файл", None, -1))
        self.menu_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Справка", None, -1))
        self.action_open.setText(QtWidgets.QApplication.translate("MainWindow", "Открыть", None, -1))
        self.action_exit.setText(QtWidgets.QApplication.translate("MainWindow", "Выход", None, -1))
        self.action_Qt.setText(QtWidgets.QApplication.translate("MainWindow", "О Qt", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "О программе", None, -1))
        self.action_open_as.setText(QtWidgets.QApplication.translate("MainWindow", "Открыть как...", None, -1))
        self.action_save.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить", None, -1))
        self.action_save_as.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить как...", None, -1))

