# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_read_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_read_file.setObjectName("pushButton_read_file")
        self.gridLayout.addWidget(self.pushButton_read_file, 2, 0, 1, 1)
        self.pushButton_save_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_file.setObjectName("pushButton_save_file")
        self.gridLayout.addWidget(self.pushButton_save_file, 3, 0, 1, 1)
        self.toolButton_output_file = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_output_file.setObjectName("toolButton_output_file")
        self.gridLayout.addWidget(self.toolButton_output_file, 3, 2, 1, 1)
        self.toolButton_input_file = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_input_file.setObjectName("toolButton_input_file")
        self.gridLayout.addWidget(self.toolButton_input_file, 2, 2, 1, 1)
        self.lineEdit_output_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output_file.setObjectName("lineEdit_output_file")
        self.gridLayout.addWidget(self.lineEdit_output_file, 3, 1, 1, 1)
        self.pushButton_clean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.gridLayout.addWidget(self.pushButton_clean, 4, 0, 1, 1)
        self.lineEdit_input_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_file.setObjectName("lineEdit_input_file")
        self.gridLayout.addWidget(self.lineEdit_input_file, 2, 1, 1, 1)
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.gridLayout.addWidget(self.pushButton_convert, 5, 0, 1, 1)
        self.checkBox_join = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_join.setObjectName("checkBox_join")
        self.gridLayout.addWidget(self.checkBox_join, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_input.setReadOnly(True)
        self.plainTextEdit_input.setObjectName("plainTextEdit_input")
        self.horizontalLayout.addWidget(self.plainTextEdit_input)
        self.plainTextEdit_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_output.setObjectName("plainTextEdit_output")
        self.horizontalLayout.addWidget(self.plainTextEdit_output)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_open_as = QtWidgets.QAction(MainWindow)
        self.action_open_as.setObjectName("action_open_as")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_open_as)
        self.menu.addSeparator()
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_save_as)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.action_about)
        self.menu_2.addAction(self.action_Qt)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        self.action_open.triggered.connect(MainWindow.load_file)
        self.pushButton_convert.clicked.connect(MainWindow.convert_srt_to_txt)
        self.pushButton_clean.clicked.connect(MainWindow.clean_srt)
        self.action_about.triggered.connect(MainWindow.show_about_window)
        self.action_Qt.triggered.connect(MainWindow.show_aboutqt_window)
        self.toolButton_input_file.clicked.connect(MainWindow.open_file_dialog)
        self.pushButton_read_file.clicked.connect(MainWindow.load_file)
        self.toolButton_output_file.clicked.connect(MainWindow.set_txt_file_name)
        self.pushButton_save_file.clicked.connect(MainWindow.save_file)
        self.action_open_as.triggered.connect(MainWindow.open_file_dialog)
        self.action_save.triggered.connect(MainWindow.save_file)
        self.action_save_as.triggered.connect(MainWindow.save_file_dialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRTtoTXT"))
        self.pushButton_read_file.setText(_translate("MainWindow", "Загрузить"))
        self.pushButton_save_file.setText(_translate("MainWindow", "Сохранить"))
        self.toolButton_output_file.setText(_translate("MainWindow", "..."))
        self.toolButton_input_file.setText(_translate("MainWindow", "..."))
        self.pushButton_clean.setText(_translate("MainWindow", "Очистка файла от HTML-разметки"))
        self.pushButton_convert.setText(_translate("MainWindow", "Конвертировать"))
        self.checkBox_join.setText(_translate("MainWindow", "Объединение строк в предложения"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_Qt.setText(_translate("MainWindow", "О Qt"))
        self.action_about.setText(_translate("MainWindow", "О программе"))
        self.action_open_as.setText(_translate("MainWindow", "Открыть как..."))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_save_as.setText(_translate("MainWindow", "Сохранить как..."))

